### ISSUE TITLE
Pandas future warning around sorting

### ISSUE THREAD

**Issue by ymyke** [hydrosquall/tiingo-python#392]
* Tiingo Python version: 0.12.0
* Python version: 3.7.5
* Operating System: Windows 10

### Description

Used get_dataframe() to retrieve a tickers historical price data.

### What I Did

The function works and produces the expected results, but it also produces a warning:

```
C:\Users\[...]\lib\site-packages\tiingo\api.py:270: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

prices = pd.concat([prices, df[stock]], axis=1)
```

**Comment by hydrosquall** [comment]
Thanks for reporting this @ymyke! Found some more information about this issue here: https://stackoverflow.com/questions/50501787/python-pandas-user-warning-sorting-because-non-concatenation-axis-is-not-aligne

I'm going to retain the current behavior and go with the second solution, unless we hear from others suggesting otherwise.

**Comment by ymyke** [comment]
Thanks!
