### ISSUE TITLE
[platform] End support for Python 2 + Python 3.5

### ISSUE THREAD

**Issue by hydrosquall** [hydrosquall/tiingo-python#601]
Python below 3.6 is failing various tests, and I don't see a compelling reason to keep supporting that in the next release. Python 2 was sunset over a year ago ( https://www.python.org/doc/sunset-python-2/ ). Thanks @RJTK for the suggestion. 

Things we need to change to be able to do this

- [x] Remove the tests below 3.5 from github workflow testing matrix
- [x] Remove mentions of anything below python 3.6 in various metadata files (setup.py, etc)
- [x] Remove the part of the publishing process that builds a python 2.x distribution

Things this will unlock

- [x] Our CI will pass again
- [x] We can use `black` to format the whole codebase once over #663 
- [x] We can add `black` to the CI process so people don't need to be manually checking/editing their code style #663 

Users who are unable to migrate past python 2 can continue to use the current release of Tiingo (`0.13.0`). If this becomes an issue for anyone, please leave a note in this thread and we'll see if we can recommend an alternate solution.

## Notes on the ecosystem moving along

- Our readthedocs build started failing recently, it's because the websockets client wasn't installable on Python 2. Upgrading to python 3 ( see https://readthedocs.org/projects/tiingo-python/builds/14476185/ )

**Comment by GenusGeoff** [comment]
I fully support ending backward compatibility. I didn't want to be rude and suggest this earlier, but Python 2 is not only dead but unsupported at this time. For any institution still using Python 2, they can use one of the older branches or otherwise patch their modules with newer changes in a Python 2 compatible way. It's not a good use of resources to continue to support backward compatibility.

**Comment by hydrosquall** [comment]
Completed in #663
