### ISSUE TITLE
CCU empty volume?

### ISSUE THREAD

**Issue by mingwugmail** [hydrosquall/tiingo-python#665]
* Tiingo Python version: 0.14.0
* Python version: 3.6.9
* Operating System: Ubuntu 18.04.2 LTS

### Description

```
  start = "1900-01-01"  # get all
  df = client.get_dataframe(symbol, startDate=start)
  df.to_csv(fn)  # save the original tiingo df for the record
```

the data I got:
```
date,close,high,low,open,volume,adjClose,adjHigh,adjLow,adjOpen,adjVolume,divCash,splitFactor
1993-02-22 00:00:00+00:00,40.3,40.3,39.375,40.0,,9.2234672972,9.2234672972,9.0117624027,9.1548062503,,0.0,1.0
1993-02-23 00:00:00+00:00,40.95,40.95,39.675,40.625,,9.3722328988,9.3722328988,9.0804234495,9.297850098,,0.0,1.0

... all the way down to:

2000-12-29 00:00:00+00:00,53.75,53.75,52.35,52.35,,13.0179428367,13.0179428367,12.6788708372,12.6788708372,,0.0,1.0
```

Notice: all the volume, and adjVolume is empty '', if there is no data, should this be 0?

And this issue also happens on these symbols:
```
$ grep -l ',,' *.csv
CCU.csv
EEH.csv
FLMI.csv
IIGV.csv
ISDX.csv
JIGB.csv
OPER.csv
TAGS.csv
UCIB.csv
```

Not sure if this is a tiingo-python issue, or tiingo server data issue.

**Comment by hydrosquall** [comment]
Hi, thanks for the report!

My initial reaction is that `0` is not the same thing as `no data` (since real data could report a value of 0 for those fields), so I think it's intended to not overload `0` to both mean `unknown` and `nothing.`

Another option could be an explicit "no data" code like "N/A" or negative numbers, but we aren't doing any special processing inside the client for empty data values. `support@tiingo.com` may be able to help resolve empty data issues with specific tickers. Please feel free to reopen this issue if it turns out the issue is specific to the python library.
