### ISSUE TITLE
(api) per-minute data not available for SSE and SZSE

### ISSUE THREAD

**Issue by FlynnMa** [hydrosquall/tiingo-python#698]
* Tiingo Python version: 0.14.0
* Python version:  3.8.10
* Operating System: ubuntu20.02

### Description
Hello,

I am trying to get minutes data for Chinese A stock, since 3 weeks ago, it no longer works, now it returns error like: "KeyError: "None of ['date'] are in the columns"

### What I Did

Here I test with the asset '600918' from SSE, in fact any stock listed from SSE and SZSE does not work

```
from tiingo import TiingoClient

config = {}

# To reuse the same HTTP Session across API calls (and have better performance), include a session key.
config['session'] = True

# If you don't have your API key as an environment variable,
# pass it in via a configuration dictionary.
config['api_key'] = "my api key"

# Initialize
client = TiingoClient(config)

df = client.get_dataframe('600918',
                                      startDate='2021-11-15', frequency='1Min')

print(df)
```

### It used to be working perfect before Nov.4.2021
I didn't change anything from my laptop

![image](https://user-images.githubusercontent.com/12571759/142346901-ec7fb9cb-f92d-40f9-ab43-04c310fa041e.png)

**Comment by hydrosquall** [comment]
Hi @FlynnMa , thanks for the report. This issue seems specific to the Shanghai and Shenzhen stock exchanges as you noted (SSE and SZSE)

To isolate the issue, I have 2 questions:

- Does the issue persist for stocks from other exchanges?
- Is the data available at other frequencies (such as hourly, daily) for these exchanges?

This client library doesn't control the upstream data, I'd suggest contacting the Tiingo team directly (email address on this page https://api.tiingo.com/ ) to see if something has changed recently about data from these providers.

**Comment by FlynnMa** [comment]
Hi @hydrosquall,

the issue only happens on SSE/SZSE stocks, the data is available for daily, other frequencies less than daily does not work.

I have contacted Tiingo, it seems not supported from tiingo, but strange that it seems used to work from this python lib 


Thanks!

**Comment by tiingo** [comment]
Hi, we do not cover intraday data for Shanghai or Shenzen exchanges, only End-of-Day. We have never covered this data so our endpoints would not have returned intraday data.
